name: app
description: "TalentFlow - Job matching application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.10.3
  go_router: ^13.2.0
  http: ^1.5.0
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1
  flutter_animate: ^4.5.0
  flutter_native_splash: ^2.4.6
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  image_picker: ^1.2.0
  flutter_card_swiper: ^7.0.1
  file_picker: ^8.3.7
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/images/

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/icon.png
  android: true
  ios: true
  android_12:
    color: "#FFFFFF"
    image: assets/images/icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
